import React from 'react'
import Head from 'next/head'
import s from '@/styles/Home.module.scss'

export default function Home() {
  React.useEffect(() => {
    fetch('https://api.yookassa.ru/v3/payments', {
      method: 'POST',
      body: JSON.stringify({
        amount: {
          value: '100.00',
          currency: 'RUB',
        },
        payment_method_data: {
          type: 'bank_card',
        },
        confirmation: {
          type: 'redirect',
          return_url: 'https://nikitavakula.vercel.app/',
        },
        metadata: {
          test: '123 123',
        },
      }),
    })
      .then((res) => res.json())
      .then((res) => {
        console.log(res)
      })
      .catch((err) => {
        console.log(err)
      })
      .finally(() => {})
  }, [])

  return (
    <>
      <Head>
        <title>Yookassa Training</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <div className={s.root}>Hello</div>
    </>
  )
}
